name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: testing
          AWS_ACCESS_KEY_ID: 1
          AWS_SECRET_ACCESS_KEY: 1
          AWS_S3_BUCKET: 1
        run: |
          

  deployment:
       needs: test_suite
       runs-on: ubuntu-latest
       steps:
         - name: Fresh clone & repo install
           uses: appleboy/ssh-action@master
           with:
             host: 3.229.176.191
             username: github-actions
             key: ${{ secrets.JISHOAPP_KEY }}
             port: 22
             script: |
               rm -rf jisho2
               git clone https://github.com/joshlittlefield/jisho2.git
               python3 -m venv /home/github-actions/jisho2/venv
               source /home/github-actions/jisho2/venv/bin/activate
               pip install -r /home/github-actions/jisho2/requirements.txt
               chmod +x /home/github-actions/jisho2/script.sh
               /home/github-actions/jisho2/./script.sh
               mv /home/github-actions/jisho2/src/migrations /home/github-actions/jisho/
               cd /home/github-actions/jisho2
               export FLASK_APP=src/main.py
               flask db-custom drop
               flask db upgrade
               flask db-custom seed
